	
/* 5) MAGNITUDE- Compare the measure values by categories

Task 1- Find the total customers by countries
Task 2- Find the total customers by gender
Task 3- Find the total products by category
Task 4- What is the average cost in each country?
Task 5- What is the total revenue generated for each country?
Task 6- Find the total revenue generated by each customer
Task 7- What is the distribution of sold items across countries?
*/

-- Task 1
SELECT 
country,
COUNT(customer_key) AS total_customers_by_country
FROM gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC;

--Task 2
SELECT 
gender,
COUNT(customer_key) AS total_customers_by_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC;

--Task 3
SELECT
category,
COUNT(product_key) AS total_products_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY COUNT(product_key) DESC ;

-- Task 4
SELECT
category,
AVG(cost) AS average_cost_by_category
FROM gold.dim_products
GROUP BY category
ORDER BY AVG(cost) DESC;

-- Task 5
SELECT
p.category,
SUM(COALESCE(f.sales_amount,0)) AS total_revenue_by_category
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON f.product_key=p.product_key
GROUP BY p.category
ORDER BY SUM(COALESCE(f.sales_amount,0)) DESC ;

-- Task 6
SELECT
c.customer_key,
CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
SUM(COALESCE(f.sales_amount,0))AS total_revenue_by_customer
FROM gold.fact_sales as f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key=c.customer_key
GROUP BY c.customer_key,c.first_name,c.last_name
ORDER BY SUM(COALESCE(f.sales_amount,0)) DESC;

-- Task 7
SELECT
c.country,
SUM(f.quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON f.customer_key=c.customer_key
GROUP BY c.country
ORDER BY SUM(f.quantity) DESC
